import React, { useEffect } from 'react'
import './PolicyPage.scss'
import $ from 'jquery';
import { useNavigate } from 'react-router-dom';


const PolicyPage = () => {
    let navigate = useNavigate();
    useEffect(() => {
        $(function () {
            $(window).scrollTop(0);
        });
    }, [])

    // header scroll
    useEffect(() => {
        const handleScroll = () => {
            const scrollPosition = window.scrollY;
            // Check if scroll position is at 100vh
            if (scrollPosition >= 5) {
                $(".header").addClass("shrinked");
            } else {
                $(".header").removeClass("shrinked");

            }
        }
        window.addEventListener('scroll', handleScroll);
        // Clean up event listener
        return () => window.removeEventListener('scroll', handleScroll);
    }, []);

    return (
        <div className=' policy-page'>

            <section className="banner">
                <div className="inner">
                    <h1
                        className="main-heading"
                      >
                       Terms and Conditions
                    </h1>

                </div>

            </section>
          
            <div className='sec-2'>

  <div className='section'>
    <h3 className='title'>Terms and Conditions</h3>
    <p><strong>Effective Date:</strong> 12 July 2025</p>
    <p>Welcome to the Cloudnet Travels website. By accessing or using our website, including travel packege booking, you agree to the following Terms and Conditions. Please read them carefully.</p>
  </div>
 <div className='section'>
    <h3 className='title'>1. Electronic Record Statement</h3>
    <p>This document is an electronic record in terms of the Information Technology Act, 2000 and applicable rules thereunder, as amended by the provisions pertaining to electronic records in various statutes. This electronic record is generated by a computer system and does not require any physical or digital signatures.</p>
  </div>

  <div className='section'>
    <h3 className='title'>2. Publication & Platform Ownership</h3>
    <p>This document is published in accordance with Rule 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011, requiring the publication of rules, regulations, privacy policy, and Terms of Use for the domain name <a href="https://cloudnettravels.com/">https://cloudnettravels.com/</a> ('Website'), including the related mobile site and application ('Platform').</p>
    <p>The Platform is owned by CLOUDNET TRAVELS, a company incorporated under the Companies Act, 1956, with its registered office at 31108, Millath Complex, Palakkutty, Koduvally, Kozhikode, India (hereinafter referred to as ‘Platform Owner’, 'we', 'us', 'our').</p>
  </div>

  <div className='section'>
    <h3 className='title'>3. Acceptance of Terms</h3>
    <p>Your use of the Platform, its services, and tools is governed by these Terms of Use, along with the applicable policies incorporated herein by reference. By using the Platform, you are contracting with the Platform Owner and agree to be bound by these Terms of Use and all applicable policies. These Terms may be modified at any time without prior notice, and it is your responsibility to review them periodically.</p>
    <p>For the purpose of these Terms of Use, ‘you’, 'your', or ‘user’ shall mean any natural or legal person who has agreed to become a user/buyer on the Platform.</p>
    <p><strong>ACCESSING, BROWSING, OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO THESE TERMS OF USE.</strong></p>
  </div>

  <div className='section'>
    <h3 className='title'>4. User Obligations</h3>
    <ul>
      <li>Provide true, accurate, and complete information during and after registration.</li>
      <li>Be responsible for all activities conducted through your registered account.</li>
      <li>Use the Platform and Services at your own risk; we are not liable for any issues arising from your usage.</li>
      <li>Refrain from claiming intellectual property rights over Platform content, which includes but is not limited to the design, layout, look, and graphics.</li>
      <li>Avoid unauthorized use of the Platform or Services, which may result in legal action.</li>
      <li>Pay applicable charges associated with availing our Services.</li>
      <li>Not use the Platform or Services for any unlawful or prohibited purposes.</li>
    </ul>
  </div>

  <div className='section'>
    <h3 className='title'>5. Third-Party Links</h3>
    <p>The Platform and Services may contain links to third-party websites. When accessing these links, you will be governed by the terms and policies of such websites. These are provided solely for your convenience.</p>
  </div>

  <div className='section'>
    <h3 className='title'>6. Legal Obligations & Contracts</h3>
    <p>By initiating a transaction for availing Services, you enter into a legally binding and enforceable contract with the Platform Owner. You shall indemnify and hold harmless the Platform Owner, affiliates, and employees from any claims, penalties, or damages arising from your breach of these Terms, Privacy Policy, other policies, or any applicable laws.</p>
  </div>

  <div className='section'>
    <h3 className='title'>7. Force Majeure</h3>
    <p>The parties shall not be liable for any failure to perform obligations under these Terms if prevented or delayed by a force majeure event.</p>
  </div>

  <div className='section'>
    <h3 className='title'>8. Governing Law & Jurisdiction</h3>
    <p>These Terms are governed by the laws of India. All disputes shall be subject to the exclusive jurisdiction of the courts in Kozhikode, Kerala.</p>
  </div>

  <div className='section'>
    <h3 className='title'>9. Contact</h3>
    <p>All concerns or communications regarding these Terms must be sent using the contact information provided on our website.</p>
  </div>

</div>


        </div>


    )
}

export default PolicyPage