# Generated by Django 5.2.4 on 2025-09-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=100)),
                ('office_address', models.TextField(max_length=500)),
                ('home_address', models.TextField(max_length=500)),
                ('alternative_phone_number', models.CharField(max_length=20)),
                ('govt_id_number', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField()),
                ('is_id_verified', models.BooleanField(default=False)),
                ('joined_on', models.DateField()),
            ],
        ),
    ]
