# Generated by Django 5.2.4 on 2025-09-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
