# Generated by Django 5.2.4 on 2025-09-07 06:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='joined_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
