# Generated by Django 5.2.4 on 2025-09-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_wallettransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallettransaction',
            old_name='created_at',
            new_name='initiated_at',
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='payment_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='processing', max_length=20),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='closing_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
