# Generated by Django 5.2.4 on 2025-09-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_wallettransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='wallet_balance',
            field=models.DecimalField(
                max_digits=12,
                decimal_places=2,
                default=0,
            ),
        ),
    ]