# Generated by Django 5.2.4 on 2025-09-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_rename_created_at_wallettransaction_initiated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='credit_or_debit',
            field=models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], default='debit', max_length=10),
        ),
        migrations.AlterField(
            model_name='agency',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
