# Generated by Django 5.2.4 on 2025-09-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0006_wallettransaction_credit_or_debit_alter_agency_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
