# Generated by Django 5.2.4 on 2025-09-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0007_alter_wallettransaction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='payment_method',
            field=models.CharField(choices=[('phonepe', 'PhonePe'), ('booking', 'By System for booking'), ('manual', 'Manual')], default='phonepe', max_length=20),
        ),
    ]
