# Generated by Django 5.2.4 on 2025-09-21 04:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agency', '0006_wallettransaction_credit_or_debit_alter_agency_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=100)),
                ('total_pax', models.IntegerField()),
                ('adult', models.IntegerField(default=0)),
                ('child', models.IntegerField(default=0)),
                ('infant', models.IntegerField(default=0)),
                ('adult_info', models.JSONField(blank=True, default=list)),
                ('child_info', models.JSONField(blank=True, default=list)),
                ('infant_info', models.JSONField(blank=True, default=list)),
                ('airiq_response', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='agency.wallettransaction')),
            ],
        ),
    ]
