# Generated by Django 5.2.4 on 2025-09-26 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_ticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='ticket_id',
            field=models.TextField(),
        ),
    ]
