# Generated by Django 5.2.4 on 2025-09-27 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_amount_booking_destination_booking_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='source',
            new_name='origin',
        ),
    ]
