# Generated by Django 5.2.4 on 2025-09-11 09:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIRIQLoginToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('token_type', models.CharField(default='bearer', max_length=20)),
                ('expiration', models.IntegerField(default=3600)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_logged_in', models.DateTimeField(default=django.utils.timezone.now)),
                ('balance_at_login_time', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
